// Generated by https://quicktype.io

export interface SuccessTrueDataID95D81754407345AaBc2D559Cc40E8002NameAlimentoCaseroURLImagenHTTPS04ContenedoresnolvisCOMStorageCategorias9C7E3217963D41F0B977D843Cd49C67FPNGCreatedAt03172022UpdatedAt03172022MessageCategoriasFetched {
    success: boolean;
    data:    Datum[];
    message: string;
}

export interface Datum {
    id:         string;
    name:       string;
    url_imagen: string;
    created_at: string;
    updated_at: string;
}
