// Generated by https://quicktype.io

export interface Ciudades {
    success: boolean;
    data:    Datum[];
    message: string;
}

export interface Datum {
    id:         string;
    name:       string;
    created_at: string;
    updated_at: string;
}
 export interface simpleCiudades{
    id: string;
    name: string;
    url: string;
 }