// Generated by https://quicktype.io

export interface SuccessTrueDataID95Df9F723374408BA18525269E8F3443CiudadesIDNullSectoresID95Df9F722Ab44D3CA5Ef7105Dec742E0BusinessIDNullURLImagenHTTPS04ContenedoresnolvisCOMStorageSectores57E1B0Ce3Ef84512Bc6436E1D5002F5AJpgCreatedAt03212022UpdatedAt03212022ID95Df9F7235514E55Aa211F3Fcca97BaeCiudadesIDNullSectoresID95Df9F722Ab44D3CA5Ef7105Dec742E0BusinessIDNullURLImagenHTTPS04ContenedoresnolvisCOMStorageSectores2229A44A78284661B96DBa6D873387EaJpgCreatedAt03212022UpdatedAt03212022ID95Df9F72368E4Ad4A60E9A79484576AdCiudadesIDNullSectoresID95Df9F722Ab44D3CA5Ef7105Dec742E0BusinessIDNullURLImagenHTTPS04ContenedoresnolvisCOMStorageSectores8094851E318F4Db583D082E22D389522JpgCreatedAt03212022UpdatedAt03212022MessageGaleriaDeImagenesDeSectorFetched {
    success: boolean;
    data:    Datum[];
    message: string;
}

export interface Datum {
    id:          string;
    ciudades_id: null;
    sectores_id: string;
    business_id: null;
    url_imagen:  string;
    created_at:  string;
    updated_at:  string;
}
