// Generated by https://quicktype.io

export interface SuccessTrueDataID95Db8Ee6030842B49B622C630Ec85A14CiudadesIDNullSectoresID95Db8Ee6003340EbBb4C09B9D9261Ea0BusinessIDNullURLImagenHTTPS04ContenedoresnolvisCOMStorageSectores3B383A76485C450EAd543980F69B2043JpgCreatedAt03192022UpdatedAt03192022ID95Db8Ee603D447Fe9A3D4753E8Ebe9FcCiudadesIDNullSectoresID95Db8Ee6003340EbBb4C09B9D9261Ea0BusinessIDNullURLImagenHTTPS04ContenedoresnolvisCOMStorageSectoresF236Ba3F6E514470982BA5Ac5856012CJpgCreatedAt03192022UpdatedAt03192022ID95Db8Ee6078E477481062Be55D000896CiudadesIDNullSectoresID95Db8Ee6003340EbBb4C09B9D9261Ea0BusinessIDNullURLImagenHTTPS04ContenedoresnolvisCOMStorageSectoresF61D3477470646988C5465951Bf1864CJpgCreatedAt03192022UpdatedAt03192022MessageGaleriaDeImagenesDeSectorFetched {
    success: boolean;
    data:    Datum[];
    message: string;
}

export interface Datum {
    id:          string;
    ciudades_id: null;
    sectores_id: string;
    business_id: null;
    url_imagen:  string;
    created_at:  string;
    updated_at:  string;
}
